apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  devtron-cluster
  region: ap-south-1
  version: "1.19"

vpc:
  id: "vpc-xxxxxxx"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      ap-south-1a:
          id: "subnet-xxxxxxx"
          cidr: "0.0.0.0/24"
      ap-south-1b:
          id: "subnet-xxxxxxx"
          cidr: "0.0.0.0/24"

    public:
      public-ap-south-1a:
          id: "subnet-xxxxxxx"
          cidr: "0.0.0.0/25"
      public-ap-south-1b:
          id: "subnet-xxxxxxx"
          cidr: "0.0.0.0/25"

nodeGroups:
  - name: devtron-nodes
    privateNetworking: true
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.5
      instanceTypes: ["c5a.xlarge", "r5a.xlarge", "m5a.xlarge"]
      onDemandBaseCapacity: 2
      onDemandPercentageAboveBaseCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::xxxxxxxxxxxxx:policy/devtron-cluster-IAM-policy
    ssh:
      allow: true
      publicKeyName: "infra"
    volumeSize: 50
    tags:
      Component : cicd
    labels: { role: p2p-dev-nodegroup }
    kubeletExtraConfig:
        kubeReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true

  - name: ci-nodes
    privateNetworking: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 5
    instancesDistribution:
      maxPrice: 0.5
      instanceTypes: ["c5a.xlarge", "r5a.xlarge", "m5a.xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::xxxxxxxxxxxxx:policy/devtron-cluster-IAM-policy
    ssh:
      allow: true
      publicKeyName: "infra"
    volumeSize: 100
    tags:
      Component : cicd
    labels: {purpose: ci}
    taints:
      dedicated: "ci:NoSchedule"
    kubeletExtraConfig:
        kubeReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "200m"
            memory: "200Mi"
            ephemeral-storage: "1Gi"
        evictionHard:
            memory.available:  "200Mi"
            nodefs.available: "10%"
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true