apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-except-secret-pod-exec
rules:
- apiGroups:
    - ""
  resources:
  - bindings                                
  - configmaps                        
  - endpoints                        
  - events                            
  - namespaces                        
  - nodes                             
  - persistentvolumeclaims           
  - persistentvolumes                 
  - pods    
  - pods/log                        
  - podtemplates                                              
  - replicationcontrollers          
  - resourcequotas                  
  - serviceaccounts                   
  - services    
  - limitranges
  verbs: ["get", "list", "watch", "create", "update", "delete"]     
- apiGroups: 
  - extensions
  - apiextensions.k8s.io
  - authentication.k8s.io
  - admissionregistration.k8s.io
  - apisix.apache.org
  - configuration.konghq.com
  - generators.external-secrets.io
  - external-secrets.io
  - events.k8s.io
  - apiregistration.k8s.io
  - flowcontrol.apiserver.k8s.io
  - mongodb.com
  - apps.projectsveltos.io
  - mongodbcommunity.mongodb.com
  resources: ["*"]
  verbs: ["list"]
- apiGroups: 
  - apps
  - batch
  - policy
  - kyverno.io
  - networking.k8s.io
  - storage.k8s.io
  - snapshot.storage.k8s.io
  - rbac.authorization.k8s.io
  - discovery.k8s.io
  - argoproj.io
  - autoscaling
  - cert-manager.io
  - certificates.k8s.io
  - installer.devtron.ai
  - acme.cert-manager.io
  - fluentbit.fluent.io
  - monitoring.coreos.com
  - reports.kyverno.io
  - wgpolicyk8s.io
  - fluentd.fluent.io
  -  scheduling.k8s.io
  - pincher.devtron.ai
  - monitoring.grafana.com
  - node.k8s.io
  - eventing.keda.sh
  - keda.sh
  - karpenter.k8s.aws
  - karpenter.sh
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["get", "list", "watch"]
---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd-user-except-secret-pod-exec
  namespace: devtroncd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-except-secret-pod-exec-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-except-secret-pod-exec
subjects:
  - kind: ServiceAccount
    name: cd-user-except-secret-pod-exec
    namespace: devtroncd
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: cd-user-except-secret-pod-exec
  name: cd-user-except-secret-pod-exec-token
  namespace: devtroncd
type: kubernetes.io/service-account-token
