apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devtron-limited-access
rules:
- apiGroups:
    - ""
  resources:
#    - secrets 
  - bindings                                
  - configmaps                        
  - endpoints                        
  - events                            
  - namespaces                        
  - nodes                             
  - persistentvolumeclaims           
  - persistentvolumes                 
  - pods    
  - pods/log                        
  - podtemplates                                              
  - replicationcontrollers          
  - resourcequotas                  
  - serviceaccounts                   
  - services    
  verbs: ["get", "list", "watch", "create", "update", "delete"]     
- apiGroups: 
  - apps
  - extensions
  - batch
  - policy
  - networking.k8s.io
  - storage.k8s.io
  - rbac.authorization.k8s.io
  - discovery.k8s.io
  - apiextensions.k8s.io
  - authentication.k8s.io
  - admissionregistration.k8s.io
  - argoproj.io
  - autoscaling
  - cert-manager.io
  - certificates.k8s.io
  - acme.cert-manager.io
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- nonResourceURLs: ["*"]
  verbs: ["get", "list", "watch"]
---          
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devtron-client-readonly
  namespace: devtroncd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devtron-client-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devtron-limited-access
subjects:
  - kind: ServiceAccount
    name: devtron-client-readonly
    namespace: devtroncd
